#!/bin/bash

# Install system packages
sudo apt-get update
sudo apt-get install python3
sudo apt-get install python3-pip
sudo apt-get install libsm6 libxext6 libxrender-dev

# Install Python packages
pip3 install opencv-python-headless
pip3 install numpy
pip3 install pyautogui
